version: "3.8"

services:
  postgres:
    container_name: api_cursos_postgres
    image: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api_cursos
